import HeaderTop from "@/app/componets/HeaderTop";
import './globals.css';
import type { Metadata } from "next";
import { Inter } from 'next/font/google';
import HeaderMain from "./componets/HeaderMain";
import Navbar from "./componets/Navbar";


const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en"> 
      <body className={inter.className}> 
        <HeaderTop />
        <HeaderMain/>
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
